replicaCount: 1
image:
  repository: jaysuzi5/otel-test
  pullPolicy: Always
  tag: otel-test-dev-latest
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 5001
ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: home.dev.com
      paths:
        - path: /api/otel-test/
          pathType: Prefix
  tls: []
resources: {}
livenessProbe:
  httpGet:
    path: /api/otel-test/v1/health
    port: 5001
  initialDelaySeconds: 30
  periodSeconds: 60
  timeoutSeconds: 3 
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /api/otel-test/v1/health
    port: 5001
  initialDelaySeconds: 5
  periodSeconds: 30
  timeoutSeconds: 3 
  failureThreshold: 3
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
otelEnv:
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: "http://otel-collector-collector.monitoring.svc.cluster.local:4317"
  - name: OTEL_SERVICE_NAME
    value: "otel-test"
  - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
    value: "true"  